title: Azimuth
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
base_font: nunito-sans
palette: blue
header:
  logo_img: images/logo.svg
  logo_img_alt: ''
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Servizi
      url: /servizi
      style: link
    - label: Pricing
      url: /pricing
      style: link
    - label: Style Guide
      url: /style-guide
      style: link
    - label: Contatti
      url: /contatti
      style: primary
footer:
  sections:
    - type: footer_text
      image: images/logo-alt.svg
      image_url: /
      image_alt: Footer logo
      content: |-
        ESCO Green Power 
        P.I.:
        Via
        93014 Mussomeli (CL)
        Tel.
    - type: footer_nav
      title: Azienda
      nav_links:
        - label: About Us
          url: /about
          style: link
        - label: Blog
          url: /blog
          style: link
        - label: Sign Up
          url: /signup
          style: link
        - label: Contact
          url: /contact
          style: link
    - type: footer_form
      title: Subscribe
      content: Stay up to date with our latest developments.
      form_id: contactForm
      hide_labels: true
      form_fields:
        - input_type: email
          name: email
          label: Email
          default_value: Enter email address
          is_required: true
      submit_label: Subscribe
  has_nav: true
  nav_links:
    - label: Terms of Service
      url: /terms-of-service
      style: link
    - label: Privacy Policy
      url: /privacy-policy
      style: link
  content: >-
    &copy; ESCO Green Power. All rights reserved. This Jamstack site by Mario
    Canalella <a href="https://www.mariocanalella.pw" target="_blank"
    rel="noopener">Mario Canalella</a>.
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
